/**
 * THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
 *
 * Generated by ../../server/scripts/generate-trpc-types.ts
 * Run 'pnpm -C packages/server gen:trpc' to regenerate this file.
 */

import { initTRPC } from "@trpc/server";
import { AuthOutputSchema, CreateWorkspaceInputSchema, DeleteWorkspaceInputSchema, LoginInputSchema, LogoutOutputSchema, RegisterInputSchema, UpdateWorkspaceInputSchema, UserProfileOutputSchema, UserUpdateInputSchema, WorkspaceSchema } from "../../index";
import { z } from "zod";

const t = initTRPC.create();

const appRouter = t.router({
auth: t.router({ login: t.procedure.input(LoginInputSchema).output(AuthOutputSchema).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
register: t.procedure.input(RegisterInputSchema).output(AuthOutputSchema).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
logout: t.procedure.output(LogoutOutputSchema).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
devLogin: t.procedure.output(AuthOutputSchema).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any) }),
user: t.router({ getProfile: t.procedure.output(UserProfileOutputSchema).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
updateProfile: t.procedure.input(UserUpdateInputSchema).output(UserProfileOutputSchema).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
deleteAvatar: t.procedure.output(UserProfileOutputSchema).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any) }),
workspace: t.router({ list: t.procedure.output(z.array(WorkspaceSchema)).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
getBySlug: t.procedure.input(z.object({ slug: z.string() })).output(WorkspaceSchema.nullable()).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
create: t.procedure.input(CreateWorkspaceInputSchema).output(WorkspaceSchema).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
update: t.procedure.input(UpdateWorkspaceInputSchema).output(WorkspaceSchema).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
delete: t.procedure.input(DeleteWorkspaceInputSchema).output(z.object({ id: z.string() })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any) })
});

export type AppRouter = typeof appRouter;
